# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"

build-master:
  stage: build
  script:
    - docker build --pull -t "$REGISTRY_IMAGE" .
    - docker push "$REGISTRY_IMAGE"
  only:
    - master
